name: Deploy Cognite Function
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        functions: [verisure_functions]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Deploy
        uses: andeplane/deploy-function-python@master
        with:
          cdf_project: verisure
          cdf_base_url: https://api.cognitedata.com
          cdf_deployment_credentials: ${{ secrets.COGNITE_API_KEY }}
          cdf_function_credentials: ${{ secrets.COGNITE_API_KEY }}
          function_path: ${{ matrix.functions }}
